create extension if not exists "pgcrypto";

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  rawg_id integer unique,
  name text not null,
  slug text default '',
  background_image text default '',
  description text default '',
  released date,
  metacritic smallint,
  platforms jsonb not null default '[]'::jsonb,
  genres jsonb not null default '[]'::jsonb,
  rawg_rating numeric(4, 2),
  website text default '',
  developers jsonb not null default '[]'::jsonb,
  publishers jsonb not null default '[]'::jsonb,
  stores jsonb not null default '[]'::jsonb,
  screenshots jsonb not null default '[]'::jsonb,
  trailers jsonb not null default '[]'::jsonb,
  steam_appid integer unique,
  steam_playtime_forever integer not null default 0,
  steam_playtime_2weeks integer not null default 0,
  steam_icon_url text default '',
  steam_imported_at timestamptz,
  steamgriddb_id integer,
  steamgrid_assets jsonb not null default '{}'::jsonb,
  status text not null default 'backlog',
  play_platform text default '',
  overall_score smallint check (overall_score between 1 and 10),
  graphics_score smallint check (graphics_score between 1 and 10),
  story_score smallint check (story_score between 1 and 10),
  gameplay_score smallint check (gameplay_score between 1 and 10),
  immersion_score smallint check (immersion_score between 1 and 10),
  music_score smallint check (music_score between 1 and 10),
  experience_tags jsonb not null default '[]'::jsonb,
  review text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.games alter column rawg_id drop not null;
alter table public.games add column if not exists steam_appid integer;
alter table public.games add column if not exists steam_playtime_forever integer not null default 0;
alter table public.games add column if not exists steam_playtime_2weeks integer not null default 0;
alter table public.games add column if not exists steam_icon_url text default '';
alter table public.games add column if not exists steam_imported_at timestamptz;

create index if not exists games_status_idx on public.games (status);
create index if not exists games_updated_at_idx on public.games (updated_at desc);
create unique index if not exists games_steam_appid_unique_idx on public.games (steam_appid);

alter table public.games enable row level security;

grant usage on schema public to service_role;
grant all privileges on table public.games to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists "No browser access to games" on public.games;
create policy "No browser access to games"
on public.games
for all
using (false)
with check (false);

create table if not exists public.game_comments (
  id uuid primary key default gen_random_uuid(),
  game_id text not null,
  rawg_id integer,
  nickname text not null,
  content text not null,
  image_url text default '',
  rating integer,
  status text not null default 'approved',
  created_at timestamptz not null default now(),
  constraint game_comments_nickname_length check (char_length(trim(nickname)) between 1 and 20),
  constraint game_comments_content_length check (char_length(trim(content)) between 1 and 300),
  constraint game_comments_rating_range check (rating is null or rating between 1 and 10),
  constraint game_comments_status_allowed check (status in ('approved', 'pending', 'hidden'))
);

alter table public.game_comments add column if not exists image_url text default '';

create index if not exists game_comments_game_id_idx on public.game_comments (game_id);
create index if not exists game_comments_created_at_idx on public.game_comments (created_at desc);

alter table public.game_comments enable row level security;

grant all privileges on table public.game_comments to service_role;

drop policy if exists "No browser access to game comments" on public.game_comments;
create policy "No browser access to game comments"
on public.game_comments
for all
using (false)
with check (false);
