# Generated by Django 4.2.30 on 2026-06-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_developers_game_publishers_game_screenshots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steamgrid_assets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='steamgriddb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
